export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONE = 'REGISTER_RESPONE';
export const GET_REGISTER_FORM_DATA = 'GET_REGISTER_FORM_DATA'

export const LOGIN_RQUEST = 'LOGIN_RQUEST';
export const LOGIN_RESPONE = 'LOGIN_RESPONE';
export const GET_LOGIN_FORM_DATA = 'GET_LOGIN_FORM_DATA'
// export const SHOW_USER_INFO = 'SHOW_USER_INFO';
export const RQUEST_USER_INFO = 'RQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'
